### ISSUE TITLE
Display X Axis value to the label or on the lines 

### ISSUE THREAD

**Issue by pvignesh92** [elastic/timelion#140] opened 2016-06-15 07:31 UTC
We are building charts to compare the data across timeframes like this week Vs last week, this month Vs last month. We could see the appropriate values of  y axis ( this week data and last week data) in the labels but the timestamp is not getting displayed. 

Though we have dates displayed as intervals in a gap of 1 week, it would be better if we get to see the values against the appropriate date,. Is it possible to achieve this is timelion now. Kindly confirm,

**Comment by rashidkpc** [comment] 2016-06-30 11:48
Dupe of https://github.com/elastic/timelion/issues/89

**Closed by rashidkpc** 2016-06-30 11:48 UTC
